/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mx.tecnm.cdhidalgo.podiatryclinic.gui;

/**
 *
 * @author tony
 */
public class Edit extends javax.swing.JPanel {

    /**
     * Creates new form Register
     */
    public Edit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        secondnameLabel = new javax.swing.JLabel();
        secondnameField = new javax.swing.JTextField();
        sexLabel = new javax.swing.JLabel();
        sexComboBox = new javax.swing.JComboBox<>();
        borndateLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        observationsField = new javax.swing.JTextArea();
        observationsLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        bornDateTextField = new javax.swing.JFormattedTextField();
        dateFormatLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bgLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        paneLabel.setText("Edit Patitent");
        add(paneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));
        add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 156, -1));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameLabel.setText("Name");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 103, -1, -1));

        secondnameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        secondnameLabel.setText("Second Name");
        add(secondnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 137, -1, -1));
        add(secondnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 156, -1));

        sexLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sexLabel.setText("Sex");
        add(sexLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 189, -1, -1));

        sexComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        add(sexComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, -1));

        borndateLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        borndateLabel.setText("Born date");
        add(borndateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        emailLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailLabel.setText("Email");
        add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        emailField.setToolTipText("name@email.com");
        add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 170, -1));

        phoneLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phoneLabel.setText("Phone");
        add(phoneLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));
        add(phoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 133, -1));

        observationsField.setColumns(20);
        observationsField.setRows(5);
        jScrollPane1.setViewportView(observationsField);
        observationsField.getAccessibleContext().setAccessibleName("");

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 460, 180));
        jScrollPane1.getAccessibleContext().setAccessibleName("Observations");

        observationsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        observationsLabel.setText("Obsertavions");
        add(observationsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 403, -1, -1));

        cancelButton.setText("Cancel");
        add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 630, -1, -1));

        saveButton.setText("Save");
        add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 630, -1, -1));

        clearButton.setText("Clear");
        add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 630, -1, -1));

        bornDateTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("M/d/yyyy"))));
        bornDateTextField.setToolTipText("M/d/yy");
        add(bornDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 168, -1));

        dateFormatLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        dateFormatLabel.setText(" (M/d/yyyy)");
        add(dateFormatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        jButton1.setText("Search");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setText("Type the patient id");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        bgLabel.setBackground(new java.awt.Color(242, 39, 222));
        add(bgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 5040, 3660));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLabel;
    private javax.swing.JFormattedTextField bornDateTextField;
    private javax.swing.JLabel borndateLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel dateFormatLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextArea observationsField;
    private javax.swing.JLabel observationsLabel;
    private javax.swing.JLabel paneLabel;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField secondnameField;
    private javax.swing.JLabel secondnameLabel;
    private javax.swing.JComboBox<String> sexComboBox;
    private javax.swing.JLabel sexLabel;
    // End of variables declaration//GEN-END:variables
}
